#!/usr/bin/env bash
# get info about holberton student domains


subs=(www lb-01 web-01 web-02)


dom_info() {
    DESTIN=$(dig "$1" | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ {print $5}')
    R_TYPE=$(dig "$1" | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ {print $4}')
    SUB="$2"
    echo "The subdomain ${SUB} is a ${R_TYPE} record and points to ${DESTIN}"
}

if (( $# > 1 )); then
    dom_info "$2.$1" "$2"
else
    for item in "${subs[@]}"; do
        dom_info "${item}.$1" "${item}"
    done
fi
