#!/usr/bin/env bash
# script transfer files to server 

PATH_TO_FILE=$1
IP=$2
USR=$3
PATH_TO_SSH_KEY=$4

if (( $# < 3 ));
    then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$SSH_PATH" -o StrictHostKeyChecking=no \
    "$PATH" "$USR"@"$PATH":~/
fi
