#!/usr/bin/env bash
# installs nginx on a server

apt-get update
apt-get install -y nginx
touch /var/www/html/index.html
echo 'Holberton School' > /var/www/html/index.html
service nginx reload
service nginx restart
