#!/usr/bin/env bash
# installs nginx on a server

apt-get update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo echo 'Holberton School' > /var/www/html/index.html
sudo service nginx restart
