#!/usr/bin/env bash
# set up a web server

apt-get update
apt-get --yes install 'nginx'
cat > '/etc/nginx/sites-available/default' << EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;
	root /var/www/html;
	index index.html;
	error_page 404 /404.html;
	location /404.html {
		internal;
	}
	location /redirect_me {
		return 301 http://example.com/;
	}
}
EOF
mkdir --parents '/var/www/html'
echo 'Holberton School' > '/var/www/html/index.html'
echo 'Ceci n'\''est pas une page' > '/var/www/html/404.html'
service nginx restart
