#!/usr/bin/env bash
# set up haproxy
sudo apt-get -y update
sudo apt-get -y install 'haproxy'
cat > '/etc/haproxy/haproxy.cfg' << EOF
frontend wolfhopkins.tech
	bind *:80
	stats uri /haproxy?stats
	default_backend web_servers
backend web_servers
	balance roundrobin
	server web-01 34.73.58.99
	server web-02 34.74.6.218
EOF
service haproxy reload
service haproxy restart
