#!/usr/bin/env bash
# set up haproxy

sudo apt-get -y update
sudo apt-get -y install 'haproxy'
cat > '/etc/haproxy/haproxy.cfg' << EOF
global
	maxconn 2000
	user haproxy
	group haproxy
defaults
	mode http
	retries 5
	timeout connect 5s
	timeout client 60s
	timeout server 60s
frontend wolfhopkins.tech
	bind *:80
	default_backend web_servers
backend web_servers
	balance roundrobin
	server web-01 34.73.58.99
	server web-02 35.231.152.200
EOF
service haproxy restart
