#!/usr/bin/env bash
# Configs a server with custom req
cp /etc/hosts ~/tempor | grep -vx '127.*localhost' /etc/hosts > /tmp/hold
echo '127.0.0.2 localhost' > ~/tempor
echo '8.8.8.8 facebook.com' >> ~/tempor
cat /tmp/hold >> ~/tempor
cp ~/tempor /etc/hosts
rm ~/tempor
rm /tmp/hold
