#!/usr/bin/env bash
# Configs a server with custom req
echo -e "127.0.0.2\tlocalhost"> /tmp/hosts.new
echo -e "8.8.8.8\tfacebook.com">> /tmp/hosts.new
cat /etc/hosts >> /tmp/hosts.new
cp -f /tmp/hosts.new /etc/hosts
